---
name: MaPharma center scrap

on:
  schedule:
    - cron: "0 */6 * * *"
  # Allow running manually
  workflow_dispatch:

jobs:

  scrape:
    name: "MaPharma centers scrap"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v2"
        with:
            token: ${{ secrets.PAT_GRZ }}
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"
      - name: "Install"
        run: make install
      - name: "MaPharma scrap new centers..."
        run: make mapharmascrap
      - name: "Copy output file"
        run: cp data/input/mapharma-centers.json .
      - name: "Get folder from data-auto"
        run: |
          git clone --branch data-auto https://github.com/CovidTrackerFr/vitemadose.git tmp/
          cp -R tmp/data/output/* data/output
          rm -rf tmp/
          cp mapharma-centers.json data/output
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated MaPharma centers
          push_options: '--force HEAD:data-auto'
